import { RoomStatus } from '#models/room'
import { DateTime } from 'luxon'

export const initialRooms = [
  {
    roomId: 'room1',
    name: 'Room 1',
    renterName: 'Aakash',
    reading: 10,
    rent: 3400,
    status: RoomStatus.occupied,
    billingHistory: {
      first: {
        rent: 3400,
        renterName: 'Aakash',
        billingAmount: 0,
        readingFrom: 0,
        readingAt: 0,
        billedAt: DateTime.now(),
      },
      second: {
        rent: 3400,
        renterName: 'Aakash',
        billingAmount: 0,
        readingFrom: 0,
        readingAt: 0,
        billedAt: DateTime.now(),
      },
      third: {
        rent: 3400,
        renterName: 'Aakash',
        billingAmount: 0,
        readingFrom: 0,
        readingAt: 0,
        billedAt: DateTime.now(),
      },
    },
  },
  {
    roomId: 'room2',
    name: 'Room 2',
    renterName: 'Sarita',
    reading: 20,
    rent: 3400,
    status: RoomStatus.occupied,
    billingHistory: {
      first: {
        rent: 3400,
        renterName: 'Sarita',
        billingAmount: 0,
        readingFrom: 0,
        readingAt: 0,
        billedAt: DateTime.now(),
      },
      second: {
        rent: 3400,
        renterName: 'Sarita',
        billingAmount: 0,
        readingFrom: 0,
        readingAt: 0,
        billedAt: DateTime.now(),
      },
      third: {
        rent: 3400,
        renterName: 'Sarita',
        billingAmount: 0,
        readingFrom: 0,
        readingAt: 0,
        billedAt: DateTime.now(),
      },
    },
  },
  {
    roomId: 'room3',
    name: 'Room 3',
    renterName: 'Roshan',
    reading: 30,
    rent: 3400,
    status: RoomStatus.occupied,
    billingHistory: {
      first: {
        rent: 3400,
        renterName: 'Roshan',
        billingAmount: 0,
        readingFrom: 0,
        readingAt: 0,
        billedAt: DateTime.now(),
      },
      second: {
        rent: 3400,
        renterName: 'Roshan',
        billingAmount: 0,
        readingFrom: 0,
        readingAt: 0,
        billedAt: DateTime.now(),
      },
      third: {
        rent: 3400,
        renterName: 'Roshan',
        billingAmount: 0,
        readingFrom: 0,
        readingAt: 0,
        billedAt: DateTime.now(),
      },
    },
  },
  {
    roomId: 'room4',
    name: 'Room 4',
    renterName: 'Saksham',
    reading: 40,
    rent: 3400,
    status: RoomStatus.occupied,
    billingHistory: {
      first: {
        rent: 3400,
        renterName: 'Saksham',
        billingAmount: 0,
        readingFrom: 0,
        readingAt: 0,
        billedAt: DateTime.now(),
      },
      second: {
        rent: 3400,
        renterName: 'Saksham',
        billingAmount: 0,
        readingFrom: 0,
        readingAt: 0,
        billedAt: DateTime.now(),
      },
      third: {
        rent: 3400,
        renterName: 'Saksham',
        billingAmount: 0,
        readingFrom: 0,
        readingAt: 0,
        billedAt: DateTime.now(),
      },
    },
  },
  {
    roomId: 'kitchen',
    name: 'Kitchen',
    renterName: 'Roshan',
    reading: 50,
    rent: 3400,
    status: RoomStatus.occupied,
    billingHistory: {
      first: {
        rent: 3400,
        renterName: 'Roshan',
        billingAmount: 0,
        readingFrom: 0,
        readingAt: 0,
        billedAt: DateTime.now(),
      },
      second: {
        rent: 3400,
        renterName: 'Roshan',
        billingAmount: 0,
        readingFrom: 0,
        readingAt: 0,
        billedAt: DateTime.now(),
      },
      third: {
        rent: 3400,
        renterName: 'Roshan',
        billingAmount: 0,
        readingFrom: 0,
        readingAt: 0,
        billedAt: DateTime.now(),
      },
    },
  },
]

export const initialBillingDetails = { key: 'Price Per Unit', value: 6 }
